FROM node:22.18.0-alpine3.22

WORKDIR /app

COPY --chown=node:node package.json package-lock.json ./
RUN npm ci

COPY --chown=node:node . ./

EXPOSE 5173

CMD ["sh", "-c", "rm -rf /app/node_modules/.vite && exec npm run dev -- --host 0.0.0.0"]
